version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: auth_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: risk_auth_db
    ports:
      - "5433:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: auth_redis
    ports:
      - "6379:6379"

  elasticsearch:
    image: elasticsearch:8.10.2
    container_name: auth_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    mem_limit: 1g

  logstash:
    image: logstash:8.10.2
    container_name: auth_logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "50000:50000"
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:8.10.2
    container_name: auth_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  postgres_data: